import "./globals.css";
import ThemeProvider from './ThemeProvider';
import ClientLayout from "../components/ClientLayout";

export const metadata = {
  title: "John Smile Mella | Frontend Developer & UI/UX Designer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="font-sans antialiased">
        <ThemeProvider>
          <ClientLayout>
            {children}
          </ClientLayout>
        </ThemeProvider>
      </body>
    </html>
  );
}
